# Generated by Django 4.1.5 on 2023-01-31 11:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="main_text",
            field=wagtail.fields.RichTextField(default=""),
        ),
    ]
