# Generated by Django 4.1.5 on 2023-02-02 11:14

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_homepage_main_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("Text", wagtail.blocks.CharBlock()),
                    ("Image", wagtail.images.blocks.ImageChooserBlock()),
                ],
                default=[],
                use_json_field=True,
            ),
        ),
    ]
