# Generated by Django 4.1.5 on 2023-03-21 09:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("Text", wagtail.blocks.CharBlock()),
                    ("Image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "TextInput",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        form_classname="InputText", required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                default=[],
                use_json_field=True,
            ),
        ),
    ]
